### ISSUE TITLE
Board(게시판) CREATE 기능 

### ISSUE THREAD

**Issue by hookim** [ssafy-pjt-naem/naem-back#41]
### 📄 Describe

게시판 CRUD중에 CREATE 기능을 작업합니다. 원래는 게시글이었는데 팀원과의 일정 조율끝에 맡은 도메인을 바꿨습니다. 

### ✅ Tasks

1. API 명세 작성하기
2. Controller 클래스 생성하기
3. Repository 클래스 생성하기 

### 🙋🏻 More

우리 하고 있어!

**Comment by bjho606** [comment]
폐기됨
